// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bwbieofbmsyvzzskduza.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ3Ymllb2ZibXN5dnp6c2tkdXphIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg2NjQyNjgsImV4cCI6MjA1NDI0MDI2OH0.0_QxcZ2LsRAyY5IuORqz6PARtbYCzS3NiqYD3CAtDK0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);